// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2U1_k0Sy8Kgch1VMpvIaDfaxUV1RcS6A',
    appId: '1:762028448106:web:fbe48b63cfd8bcc8cded13',
    messagingSenderId: '762028448106',
    projectId: 'cataloguer-flutter',
    authDomain: 'cataloguer-flutter.firebaseapp.com',
    storageBucket: 'cataloguer-flutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3sgGgY4Sm6-mpvHCEyiSW36KilRszBTM',
    appId: '1:762028448106:android:9771839c44d3814dcded13',
    messagingSenderId: '762028448106',
    projectId: 'cataloguer-flutter',
    storageBucket: 'cataloguer-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsddRy4fyLeMhWkC9MiJLBwnDF2QNqQCE',
    appId: '1:762028448106:ios:639b1e8f88c5ab9ccded13',
    messagingSenderId: '762028448106',
    projectId: 'cataloguer-flutter',
    storageBucket: 'cataloguer-flutter.appspot.com',
    iosClientId: '762028448106-h6gi5nm363f8kug5pceiclhdpmu26kca.apps.googleusercontent.com',
    iosBundleId: 'com.example.cataloguer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsddRy4fyLeMhWkC9MiJLBwnDF2QNqQCE',
    appId: '1:762028448106:ios:a9dc4225b652fe4fcded13',
    messagingSenderId: '762028448106',
    projectId: 'cataloguer-flutter',
    storageBucket: 'cataloguer-flutter.appspot.com',
    iosClientId: '762028448106-uilsa879m9j8agufbvcb7mujph311v5o.apps.googleusercontent.com',
    iosBundleId: 'com.example.cataloguer.RunnerTests',
  );
}
